# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ClassDecorator": "core_annotations.ipynb",
         "RunOnlyOnce": "core_annotations.ipynb",
         "extend_class": "core_annotations.ipynb",
         "ConfigPart": "core_config.ipynb",
         "Config": "core_config.ipynb",
         "import_config": "core_config.ipynb",
         "import_checkpoint_config": "core_config.ipynb",
         "GradientTape": "core_gradient_tape.ipynb",
         "tensor_name_table": "core_itensor.ipynb",
         "ITensorWrapper": "core_itensor.ipynb",
         "ITensor": "core_itensor.ipynb",
         "__ailab_logfile": "core_logger.ipynb",
         "__logfile": "core_logger.ipynb",
         "__logfolder": "core_logger.ipynb",
         "__log_buffer": "core_logger.ipynb",
         "__last_progress": "core_logger.ipynb",
         "__last_update": "core_logger.ipynb",
         "DEBUG_VERBOSITY": "core_logger.ipynb",
         "PRINT_STATUS": "core_logger.ipynb",
         "PRINT_INFO": "core_logger.ipynb",
         "PRINT_WARN": "core_logger.ipynb",
         "PRINT_ERROR": "core_logger.ipynb",
         "PYTHON_IGNORE_LIST": "core_logger.ipynb",
         "format_time": "core_logger.ipynb",
         "__get_all_files": "core_logger.ipynb",
         "log_value": "core_logger.ipynb",
         "log_progress": "core_logger.ipynb",
         "log_image": "core_logger.ipynb",
         "close": "core_logger.ipynb",
         "set_logger": "core_logger.ipynb",
         "get_log_path": "core_logger.ipynb",
         "get_timestamp": "core_logger.ipynb",
         "create_checkpoint_structure": "core_logger.ipynb",
         "status": "core_logger.ipynb",
         "info": "core_logger.ipynb",
         "warn": "core_logger.ipynb",
         "error": "core_logger.ipynb",
         "warn_once": "model_module.ipynb",
         "Module": "model_module.ipynb"}

modules = ["core/annotations.py",
           "core/config.py",
           "core/gradient_tape.py",
           "core/itensor.py",
           "core/logging.py",
           "model/module.py"]

git_url = "https://github.com/penguinmenac3/babilim/tree/master/"


def custom_doc_links(name): return None
