# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ClassDecorator": "core_annotations.ipynb",
         "RunOnlyOnce": "core_annotations.ipynb",
         "extend_class": "core_annotations.ipynb",
         "ConfigPart": "core_config.ipynb",
         "Config": "core_config.ipynb",
         "import_config": "core_config.ipynb",
         "import_checkpoint_config": "core_config.ipynb",
         "GradientTape": "core_gradient_tape.ipynb",
         "tensor_name_table": "core_itensor.ipynb",
         "ITensorWrapper": "core_itensor.ipynb",
         "ITensor": "core_itensor.ipynb",
         "__log_file": "core_logger.ipynb",
         "__checkpoint_path": "core_logger.ipynb",
         "__last_progress": "core_logger.ipynb",
         "__last_update": "core_logger.ipynb",
         "PYTHON_IGNORE_LIST": "core_logger.ipynb",
         "__get_all_files": "core_logger.ipynb",
         "log_value": "core_logger.ipynb",
         "log_progress": "core_logger.ipynb",
         "log_image": "core_logger.ipynb",
         "close": "core_logger.ipynb",
         "setup_minimal": "core_logger.ipynb",
         "setup": "core_logger.ipynb",
         "LogResult": "core_logger.ipynb",
         "LogCall": "core_logger.ipynb",
         "warn_once": "model_module.ipynb",
         "Module": "model_module.ipynb"}

modules = ["core/annotations.py",
           "core/config.py",
           "core/gradient_tape.py",
           "core/itensor.py",
           "core/logger.py",
           "model/module.py"]

git_url = "https://github.com/penguinmenac3/babilim/tree/master/"


def custom_doc_links(name): return None
