# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ClassDecorator": "core_annotations.ipynb",
         "RunOnlyOnce": "core_annotations.ipynb",
         "ConfigPart": "core_config.ipynb",
         "Config": "core_config.ipynb",
         "import_config": "core_config.ipynb",
         "import_checkpoint_config": "core_config.ipynb",
         "Module": "model_module.ipynb"}

modules = ["corennotations.py",
           "core\config.py",
           "model\module.py"]

git_url = "https://github.com/penguinmenac3/babilim/tree/master/"


def custom_doc_links(name): return None
